meta:
  title: Developer Portal
  description: The Surfsight API developer portal.
  siteUrl: https://portal-demo.redoc.ly
  keywords: surfsight developer portal, api portal starter, api reference docs
linkChecker:
  severity: warning
  options: 
    CheckExternal: false
logo: ./images/logo.png
enableToc: true
oasDefinitions:
  petstore: ./openapi/petstore.yaml
  surfsight: ./openapi/surfsight.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:

  - label: Developer Portal
    page: developer-portal/surfsight-concepts.md

  - label: Knowledge base
    icon: ./images/surfsight-icon-circle.png
    href: https://kb.surfsight.net/hc/en-us

  - search: true

footer:
  copyrightText: Copyright © Lytx 2021. All right reserved.
  columns:
    - group: Legal
      items:
        - label: Terms of Use
          href: 'https://redoc.ly/subscription-agreement/'
        - label: Privacy Notice
          href: 'https://redoc.ly/privacy-notice/'
        - label: Cookie Notice
          href: 'https://redoc.ly/cookie-notice/'
    - group: Support
      items:
        - label: FAQ
          page: faq.md
        - label: Contact us
          page: contact.mdx
